# ARG directive defines a variable that users can pass at build-time to the builder
ARG PYTHON_VERSION

# Use the official Python image from the Docker Hub, with the specified version
FROM python:${PYTHON_VERSION}

RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    jq \
    less \
    vim \
    wget

# Bashプロンプトの設定を追加
RUN echo 'left_prompt() {' >> ~/.bashrc && \
    echo '    local user="\[\033[0;32m\]\u🐎\[\033[0m\]"' >> ~/.bashrc && \
    echo '    local dir="\[\033[0;93m\][\w]\[\033[0m\]"' >> ~/.bashrc && \
    echo '    local next="\[\033[0;36m\]>\[\033[0m\] "' >> ~/.bashrc && \
    echo '    echo -e "\n${user} ${dir}\n${next}"' >> ~/.bashrc && \
    echo '}' >> ~/.bashrc && \
    echo 'PS1="$(left_prompt)"' >> ~/.bashrc

# Run bash when the container launches
CMD ["bash"]
